apiVersion: v1
kind: PersistentVolume
metadata:
  name: solidarytech-postgres-local
  labels:
    app: postgres
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: solidarytech-local
  hostPath:
    path: /var/lib/solidarytech/postgres
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: fiap-microservices
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: solidarytech-local
  resources:
    requests:
      storage: 10Gi
