apiVersion: apps/v1
kind: Deployment
metadata:
  name: volunteer-service
  namespace: fiap-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volunteer-service
  template:
    metadata:
      labels:
        app: volunteer-service
    spec:
      containers:
        - name: volunteer-service
          image: 245177908729.dkr.ecr.us-east-1.amazonaws.com/solidarytech/volunteer-service:b423abb
          ports:
            - containerPort: 8083
          envFrom:
            - secretRef:
                name: volunteer-secret
            - secretRef:
                name: aws-credentials
          env:
            - name: PORT
              value: "8083"
            - name: OTEL_SERVICE_NAME
              value: "volunteer-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4318"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: SERVICE_VERSION
              value: "1.0.0"
            - name: ENVIRONMENT
              value: "fiap-lab5"
          resources:
            requests:
              cpu: "15m"
              memory: "96Mi"
            limits:
              cpu: "100m"
              memory: "192Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: volunteer-service
  namespace: fiap-microservices
spec:
  type: ClusterIP
  selector:
    app: volunteer-service
  ports:
    - port: 8083
      targetPort: 8083
