apiVersion: apps/v1
kind: Deployment
metadata:
  name: ngo-service
  namespace: fiap-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ngo-service
  template:
    metadata:
      labels:
        app: ngo-service
    spec:
      containers:
        - name: ngo-service
          image: 245177908729.dkr.ecr.us-east-1.amazonaws.com/solidarytech/ngo-service:7a1fd71
          ports:
            - containerPort: 8081
          envFrom:
            - secretRef:
                name: ngo-secret
          env:
            - name: PORT
              value: "8081"
            - name: OTEL_SERVICE_NAME
              value: "ngo-service"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otel-collector.monitoring.svc.cluster.local:4318"
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: "http/protobuf"
            - name: OTEL_TRACES_EXPORTER
              value: "otlp"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: SERVICE_VERSION
              value: "1.0.0"
            - name: ENVIRONMENT
              value: "fiap-lab5"
          resources:
            requests:
              cpu: "15m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ngo-service
  namespace: fiap-microservices
spec:
  type: ClusterIP
  selector:
    app: ngo-service
  ports:
    - port: 8081
      targetPort: 8081
